name: MovieDB
options:
  bundleIdPrefix: me.william
  postGenCommand: bundle exec pod install
  createIntermediateGroups: true
configs:
  Debug: debug
  Release: releaes
targets:
  MovieDB:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    sources:
      - path: MovieDB
    dependencies:
      - framework: RxFramework.framework
        embed: false
      - framework: Core.framework
        embed: false
      - framework: ModuleManagement.framework
        embed: false
      - framework: MovieKit.framework
        embed: false
      - framework: Networking.framework
        embed: false  
      - framework: MovieList.framework
        embed: false
      - framework: MovieDetail.framework
        embed: false
    settings:
      base:
        PRODUCT_NAME: $(TARGET_NAME)
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        INFOPLIST_FILE: MovieDB/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: "me.william.MovieDB"
        MARKETING_VERSION: 1.0.1
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1,2
        ENABLE_BITCODE: NO
        # EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    postBuildScripts:
      - script: |
                echo "post build scripts"
        name: "Echo Post Build Scripts"