name: RxFramework
configs:
  Debug: debug
  Release: release
options:
  bundleIdPrefix: me.william
  deploymentTarget:
    iOS: 12.0
targets:
  RxFramework:
    type: framework
    platform: iOS
    sources:
      - path: RxFramework
    info:
      path: RxFramework/Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleName: $(PRODUCT_NAME)
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSHumanReadableCopyright: Copyright © 2022 Ajaib Technologies. All rights reserved.
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        PRODUCT_NAME: $(TARGET_NAME)
        INFOPLIST_FILE: RxFramework/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: "me.william.RxFramework"
        CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: $(inherited)
        MARKETING_VERSION: 1.0.1
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MACCATALYST: NO
        ENABLE_BITCODE: NO
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"