name: MovieDetail
configs:
  Debug: debug
  Release: release
options:
  bundleIdPrefix: me.william
  deploymentTarget:
    iOS: 13.0
targets:
  MovieDetail:
    type: framework
    platform: iOS
    sources:
      - path: MovieDetail
    scheme:
      testTargets:
        - MovieDetailTests
      gatherCoverageData: true
    dependencies:
      - framework: RxFramework.framework
        embed: false
      - framework: Networking.framework
        embed: false
      - framework: Core.framework
        embed: false
      - framework: ModuleManagement.framework
        embed: false
      - framework: MovieKit.framework
        embed: false
    info:
      path: MovieDetail/Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleName: $(PRODUCT_NAME)
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSHumanReadableCopyright: Copyright © 2022 Ajaib Technologies. All rights reserved.
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        PRODUCT_NAME: $(TARGET_NAME)
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        INFOPLIST_FILE: MovieDetail/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: "me.william.MovieDetail"
        CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: $(inherited)
        MARKETING_VERSION: 1.0.1
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MACCATALYST: NO
        ENABLE_BITCODE: NO
        # EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
  MovieDetailTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.0"
    settings:
      CODE_SIGN_STYLE: Manual
      SWIFT_VERSION: "5"
      INFOPLIST_FILE: ""
      # EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
    sources:
      - path: MovieDetailTests