name: Swift

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Fastlane scan
      run: fastlane ios testing
    - name: Generate Code Coverage
      if: steps.build.outcome == 'success'
      run: bash <(curl -s https://codecov.io/bash) -J MovieDB -t f5aea74b-61ac-4d2b-9cdd-ee6a534bbb35
      
